import { cookies } from "next/headers";

/**
 * PDF 报告水印（免费/付费分级）
 * - 免费计划：打印/导出 PDF 时叠加 "FREE PLAN" 水印
 * - 付费计划：登录后由支付 webhook 写入 qx_plan cookie（pro / api / accountant），
 *   水印自动隐藏（真正无水印导出在 Credit Pack 中提供）
 */
export async function PdfWatermark({ entity }: { entity: string }) {
  let plan = "free";
  try {
    const store = await cookies();
    plan = store.get("qx_plan")?.value ?? "free";
  } catch {
    plan = "free";
  }
  const paid = ["pro", "api", "accountant", "credit"].includes(plan);
  if (paid) return null;

  return (
    <div className="pdf-watermark" aria-hidden="true">
      FREE PLAN — Generated by qxx.uk · {entity} · {new Date().toISOString()}
      <br />
      Verify against official records: Companies House · HMRC · ONS (Open Government
      Licence v3.0)
    </div>
  );
}